// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqWRPv5I3vK-JYzSS1feHwAvXoXecfoOQ',
    appId: '1:770959535744:web:d652c016ca9480d87e0065',
    messagingSenderId: '770959535744',
    projectId: 'booc-5aca6',
    authDomain: 'booc-5aca6.firebaseapp.com',
    storageBucket: 'booc-5aca6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsMX0Qra-ManvaelfRcmUIm0-_pgNMElY',
    appId: '1:770959535744:android:7b01acbb9175108f7e0065',
    messagingSenderId: '770959535744',
    projectId: 'booc-5aca6',
    storageBucket: 'booc-5aca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq9czaivbA9Fhw3h8nPg59yNc92jHPSGE',
    appId: '1:770959535744:ios:63a9a59a16e2436d7e0065',
    messagingSenderId: '770959535744',
    projectId: 'booc-5aca6',
    storageBucket: 'booc-5aca6.appspot.com',
    iosBundleId: 'com.example.testeOlimpiadas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq9czaivbA9Fhw3h8nPg59yNc92jHPSGE',
    appId: '1:770959535744:ios:63a9a59a16e2436d7e0065',
    messagingSenderId: '770959535744',
    projectId: 'booc-5aca6',
    storageBucket: 'booc-5aca6.appspot.com',
    iosBundleId: 'com.example.testeOlimpiadas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqWRPv5I3vK-JYzSS1feHwAvXoXecfoOQ',
    appId: '1:770959535744:web:46d490954c6fafb47e0065',
    messagingSenderId: '770959535744',
    projectId: 'booc-5aca6',
    authDomain: 'booc-5aca6.firebaseapp.com',
    storageBucket: 'booc-5aca6.appspot.com',
  );
}
